---
title: "Where is the Victorian 2020 - 21 Budget Being Spent |A Breakdown by Local Government Area (LGA)" 
output: 
  flexdashboard::flex_dashboard:
    navbar:
      - { title: "Data Sources", href: "https://rpubs.com/Melsuser5/700192" }

    orientation: columns
    vertical_layout: fill
    
    
    
---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)
library(ggplot2)
library(dplyr)
library(plotly)
library(broom)
library(leaflet)
library(rgdal)
library(maptools)
library(readxl)

#interactive bar
Bar_Data <- read_excel("/users/samharvey/Desktop/Bar Data.xlsx")

#choropleth
vic.lga.shp <- readShapeSpatial("/Users/samharvey/Downloads/vmlite_lga_cm/vmlite_lga_cm.shp")
funding_by_LGA <- read_excel("/users/samharvey/desktop/funding by LGA.xlsx")
vic.lga.shp$amount <- funding_by_LGA$amount
mylabels <- paste(
  "Local Government Area: ", vic.lga.shp$lga_name, "<br/>",
  "Amount Spent (millions): $ ", vic.lga.shp$amount, "<br/>"
) %>%
  lapply(htmltools::HTML)
#title for map
htmltitle <- "<h5> Where the 2020 - 21 Budget is Being Spent | By LGA"
#define bins and colour pallett for fill colour and legend.
bins <- c(0, 10, 20, 50, 100, 200, 500, 1000, Inf)
pal <- colorBin("OrRd", domain = vic.lga.shp$amount, bins = bins)

#population graph
pop_data <- read_excel("/Users/samharvey/Desktop/Scatter data.xlsx")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Which LGA Recived the Most Funding

```{r}
map1 <-leaflet(vic.lga.shp) %>%
  addPolygons(
    fillOpacity = 0.7,
    fillColor = ~pal(vic.lga.shp$amount),
    stroke = TRUE,
    color = 'black',
    weight = 1.5,
    label = mylabels,
    labelOptions = labelOptions( 
      style = list("font-weight" = "normal", padding = "3px 8px"), 
      textsize = "13px", 
      direction = "auto"))%>%
  addLegend(pal = pal, values = ~vic.lga.shp$amount, opacity = 0.7, title = "Amount Spent (millions)",
            position = "bottomright") %>%
  addControl(html=htmltitle, position = "topright")

map1
```

Column {data-width=350}
-----------------------------------------------------------------------

### Which Areas are the Victorian Government Focusing their Spending on

```{r}
interactive_bar <- plot_ly(data = Bar_Data, y= ~Bar_Data$Area, x= ~Bar_Data$Amount, 
                           type = "bar",text = Bar_Data$Labels) %>%
  layout(yaxis = list(title ="Area of Spending"),
         xaxis = list(title = "Amount (in Billions)"))

interactive_bar
```

### Did More Populous Areas Recieve More Funding?

```{r}
pop2 <- plot_ly(pop_data, x = pop_data$Adult ,y = pop_data$`Amount spent in budget`,
                color = ~pop_data$Adult, size = ~pop_data$Adult,colors = "YlOrRd",
                text = ~paste("LGA: ", pop_data$`LGA Name`,"<br>Amount spent (millions): $", 
                              pop_data$`Amount spent in budget`,"<br>Population ",pop_data$Adult)) %>%
  layout(title = "Adult Population vs Amount Spent", xaxis = list(title = "Population"),
         yaxis = list(title = "Amount Spent in Budget (millions)") )
  
  
pop2
```

